version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.pitest:pitest-maven
    versions:
    - 1.6.2
    - 1.6.3
  - dependency-name: com.alibaba:fastjson
    versions:
    - 1.2.75
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
