image: maven:3.8.1-openjdk-8-slim
cache:
  paths:
    - $HOME/.m2/

stages:
  - test
  - publish

test:
  stage: test
  script:
    - mvn test

publish snapshots:
  stage: publish
  before_script:
    - apt update
    - apt install -y gpg
    - gpg --import <(echo "$GITLAB_PGP_PRIVATE_KEY")
  script:
    - mvn -s ./settings.xml clean deploy
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: never
    - when: on_success

publish release:
  stage: publish
  script:
    - mvn versions:set -DnewVersion=${CI_COMMIT_TAG/v}
    - mvn -s ./settings.xml clean deploy
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: on_success
